# Generated by Django 4.2 on 2025-06-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer1",
            fields=[
                ("custom_id", models.AutoField(primary_key=True, serialize=False)),
                ("custom_name", models.CharField(max_length=100)),
                ("custom_phone", models.IntegerField()),
                ("custom_gender", models.CharField(max_length=10)),
                ("custom_nationality", models.CharField(max_length=15)),
                ("custom_birthday", models.CharField(max_length=15)),
                ("custom_passport_number", models.IntegerField()),
                ("custom_passport_image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Travel1",
            fields=[
                ("travel_id", models.AutoField(primary_key=True, serialize=False)),
                ("travel_from", models.CharField(max_length=30)),
                ("travel_to", models.CharField(max_length=30)),
                ("travel_price", models.IntegerField()),
                ("travel_num_seats", models.IntegerField()),
                ("travel_start_time", models.DateTimeField()),
                ("travel_wait_time", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking1",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateField(auto_now_add=True)),
                (
                    "custom_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="albaraka.customer1",
                    ),
                ),
                (
                    "travel_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="albaraka.travel1",
                    ),
                ),
            ],
        ),
    ]
