# Generated by Django 4.2 on 2025-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vserfi_code",
            field=models.IntegerField(default=0),
        ),
    ]
