# Generated by Django 4.2 on 2025-06-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer2",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.IntegerField()),
                ("customer_gender", models.CharField(max_length=10)),
                ("customer_nationality", models.CharField(max_length=15)),
                ("customer_birthday", models.CharField(max_length=15)),
                ("customer_passport_number", models.IntegerField()),
                ("customer_passport_image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Travel2",
            fields=[
                ("travel_id", models.AutoField(primary_key=True, serialize=False)),
                ("trav_from", models.CharField(max_length=30)),
                ("trav_to", models.CharField(max_length=30)),
                ("trav_price", models.IntegerField()),
                (
                    "type_money",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("YE", "Yemeni Riyal"),
                            ("SAR", "Saudi Riyal"),
                        ],
                        default="YE",
                        max_length=3,
                    ),
                ),
                ("trav_num_seats", models.IntegerField()),
                ("trav_start_time", models.DateTimeField()),
                ("trav_wait_time", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateField(auto_now_add=True)),
                (
                    "customer_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="almotsader.customer2",
                    ),
                ),
                (
                    "trav_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="almotsader.travel2",
                    ),
                ),
            ],
        ),
    ]
