# Generated by Django 4.2 on 2025-06-02 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("almotsader", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Booking",
            new_name="Booking2",
        ),
    ]
