# Generated by Django 5.1 on 2024-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companys",
            name="com_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
