# Generated by Django 5.1 on 2024-12-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_companys_customer_id_companys_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companys",
            name="customer_birthday",
            field=models.CharField(default="customer_birthday", max_length=20),
        ),
        migrations.AddField(
            model_name="companys",
            name="customer_gender",
            field=models.CharField(default="customer_gender", max_length=20),
        ),
        migrations.AddField(
            model_name="companys",
            name="customer_nationality",
            field=models.CharField(default="customer_nationality", max_length=20),
        ),
    ]
