# Generated by Django 5.1 on 2024-12-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "company",
            "0004_companys_customer_birthday_companys_customer_gender_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companys",
            name="com_end_add_customer",
            field=models.CharField(default="/customlist/", max_length=50),
        ),
        migrations.AlterField(
            model_name="companys",
            name="com_end_add_booking",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="companys",
            name="com_end_travel",
            field=models.CharField(max_length=50),
        ),
    ]
