# Generated by Django 5.1 on 2024-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_companys_com_end_add_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companys",
            name="customer_passport_number",
            field=models.CharField(default="customer_passport_id", max_length=30),
        ),
    ]
