# Generated by Django 5.1 on 2024-12-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_alter_companys_customer_passport_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="companys",
            name="booking_date",
            field=models.CharField(default="booking_date", max_length=30),
        ),
        migrations.AddField(
            model_name="companys",
            name="customer_fk",
            field=models.CharField(default="customer_fk", max_length=30),
        ),
        migrations.AddField(
            model_name="companys",
            name="travel_fk",
            field=models.CharField(default="travel_fk", max_length=30),
        ),
    ]
