# Generated by Django 5.1 on 2024-12-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_companys_booking_date_companys_customer_fk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Travelers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("passport_number", models.BigIntegerField()),
                ("phone_number", models.BigIntegerField()),
                ("passport_image_path", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("departure_date", models.CharField(max_length=100)),
                ("travel_from", models.CharField(max_length=200)),
                ("travel_to", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الإنتظار"),
                            ("confirmed", "المؤكدة"),
                            ("cancelled", "الملغية"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("booking_code", models.CharField(max_length=200)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("cash", "نقدا"), ("transfer", "ارسال حوالة")],
                        default="transfer",
                        max_length=50,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.travelers",
                    ),
                ),
            ],
        ),
    ]
