# Generated by Django 5.1 on 2024-12-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_travelers_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="passenger",
            new_name="traveler_fk",
        ),
        migrations.AlterField(
            model_name="travelers",
            name="passport_image_path",
            field=models.ImageField(upload_to="images/%y/%m/%d"),
        ),
    ]
