# Generated by Django 5.1 on 2024-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0010_booking_user_travelers_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="com_name",
            field=models.CharField(default="albaraka", max_length=100),
        ),
    ]
