# Generated by Django 4.2 on 2024-12-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0011_booking_com_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="companys",
            name="com_image",
            field=models.ImageField(default="", upload_to="images/company/%y/%m/%d"),
        ),
    ]
